### ISSUE TITLE
Shopping Cart Tax rate not changing between languages

### ISSUE THREAD

**Issue by craigs100** [vendrhub/vendr#2]
**Describe the bug**
I have a language switcher, when used, the tax "rates" in the shopping cart remain as they were, while they are correct on product pages. This results in say an English shopping cart showing £100 VAT £20 but when switched to English UAE, it shows USD220 VAT USD44 instead of VAT USD0.

The language switcher dropdown "onchange" calls a JS function that deletes the vendr-{storeid} cookie before switching pages. This clears the shopping cart and so new products added have the correct tax rate. However, this only works locally in a Development environment, it doesn't work live in a Production environment. The site is served via CloudFlare and a rule has been added to not cache cookies containing "vendr-".

I don't know whether this is a bug or an innocent, less than ideal, implementation (which would make this a support request I suppose, sorry but there's been no response on Discord, the Our forum is now closed, the docs are really sparse on advice and the umbraco support chat isn't responding either so what are we supposed to do?),

The language switcher switches default country in the background and so therefore it should pick up that country's tax rates, but it doesn't appear to for the shopping cart. I suppose just clearing the cookie would leave open carts in the back office, so I guess the ideal might be to have the language switcher delete the cart somehow.

Umbraco V10.6.1, Vendr V3.0.12, VendrCheckout V3.0.0

**Comment by mattbrailsford** [comment]
Can you share the code for you language switcher?

**Comment by craigs100** [comment]
The switcher itself is just this:-
```
var cookieName = "vendr-" + Model.GetStore().Id;
if (cultureList.Count > 1) {
        <div class="lang-switch">
            @{
                <select id="lang-switch"  asp-for="@currentPage" onchange="deleteStoreCookie('@cookieName');if (this.value) window.location.href=this.value;">
                    @foreach (var culture in languagePickerLinks) {
                        <option value="@culture.Url">@culture.LangName@(culture.Culture == "en-ae" ? " AE" : "")</option>
                    }
                </select>
            }
        </div>
    }
```

The code that switches currency and sets the country is this:-

```
    public class CurrencyChangeNotificationHandler : INotificationHandler<RoutingRequestNotification>
    {
        private readonly ICurrencyService _currencyService;
        private readonly ICountryService _countryService;
        private readonly SessionManagerAccessor _sessionManagerAccessor;

        public CurrencyChangeNotificationHandler(ICurrencyService currencyService, ICountryService countryService, SessionManagerAccessor sessionManagerAccessor) {
            _currencyService = currencyService;
            _countryService = countryService;
            _sessionManagerAccessor = sessionManagerAccessor;
        }

        public void Handle(RoutingRequestNotification notification)
        {
            // Change currency
            var requestBuilder = notification.RequestBuilder;
            var content = requestBuilder.PublishedContent;
            
            Guid storeId = content.AncestorOrSelf<Home>().Store.Id;
            
            var countryCode = requestBuilder.Culture.ToString().Split("-")[1];
        
            var sessionManager = _sessionManagerAccessor.Instance;

            var countries = _countryService.GetCountries(storeId);
            var cultureCountry = countries.FirstOrDefault(country =>
                country.Code.Equals(countryCode, StringComparison.CurrentCultureIgnoreCase));
        
            var currency = _currencyService.GetCurrency(cultureCountry.DefaultCurrencyId.Value);
        
            sessionManager.SetDefaultPaymentCountry(storeId, cultureCountry);
            sessionManager.SetDefaultCurrency(storeId, currency, true);
        }
        
    }
```

**Comment by mattbrailsford** [comment]
Do you have a different tax class for the other country? Or it is just a different tax rate on a shared common tax class entry?

**Comment by craigs100** [comment]
As I couldn't get a single default tax class with different rates per country to work, I added a Zero tax class for UAE.  So the Standard (Default) tax class is 20% and set up just for UK and Zero is 0% just for UAE. Each are applied appropriately to the language versions of each product. None rely on on "Default", i.e. none selected.

**Comment by mattbrailsford** [comment]
Ok, well if you have different tax classes, you'll also need to update the sessions `DefaultTaxClass`

**Comment by craigs100** [comment]
Ok thanks, I'll try that.  But is that not required if you're trying to use a single default tax class with different rates per country? Or is that setting just to assist in tax calculation during the checkout? I'll report back shortly.

**Comment by mattbrailsford** [comment]
If you are using the same tax class with multiple tax rates per country it shouldn't need to be updated. It's just whether you need to re-trigger the recalculation of the order.

**Comment by craigs100** [comment]
Using the same tax class with multiple tax rates per country doesn't work.  That's why I went for a tax class per country. But now I'm finding I can't get the appropriate tax class for the country.

![image](https://github.com/vendrhub/vendr/assets/1143883/3a56a8e3-3aa9-401a-8f33-548716fc666e)

**Comment by craigs100** [comment]
Just to double, double check, I've just tried setting the same "Standard" tax class with 20% for UK and 0% for UAE on both languages of one product. Both show 20% tax in the correct currencies.  Also tried setting no tax and relying on the default "Standard" tax rate which produces the same result. Hence going for separate tax classes per language/country.  The store's default country is UK and default tax class is "Standard".

**Comment by craigs100** [comment]
Just so I can manage my client's expectations, is there an issue with Vendr's tax class system that you're looking into or is it due to my  uninformed implementation? If it's the latter, how do I get help to overcome the lack of information so I can get it working?
If it's the former, can you suggest a work around?
Thanks.

**Comment by mattbrailsford** [comment]
Hi Craig, I need a second to try and replicate this, please bare with me

**Comment by craigs100** [comment]
No probs, thanks for letting me know.  

A simpler scenario is:-
Add a product to the cart in one language, note the tax showing, then delete the product to empty the cart. Go back to product page and change language. Note the product currency and tax are correct, then add to the cart. Note the correct currency but previous language's tax class used.

**Comment by mattbrailsford** [comment]
Ok, so what is going on is that everything is working, but something else also needs updating.

The way Umbraco Commerce / Vendr works out the tax for an item is to first ask the `TaxSourceFactory` for it's approach of applying tax, which the default implementation is to apply taxes based on the destination location, so this means it'll be using the shipping country to calculate this, however in your language switcher you never actually update an orders shipping country, only it's payment country, and so if the customer has already set their shipping country it will be remembering / using whatever that is set to.

I think we do have a slight problem trying to update multiple defaults at once and updating the order at the same time, so I'd suggest implementing this like so (I've injected `IUmbracoCommerceApi` as `_commerceApi`):

```
_commerceApi.SetDefaultPaymentCountry(store.Id, country); // Don't update order
_commerceApi.SetDefaultShippingCountry(store.Id, country); // Don't update order
_commerceApi.SetDefaultCurrency(store.Id, currency); // Don't update order

var order = _commerceApi.GetCurrentOrder(store.Id);
if (order != null)
{
    _commerceApi.Uow.Execute(uow =>
    {
        var writableOrder = order.AsWritable(uow)
            .SetPaymentCountryRegion(null) // We currently need to set these to null first before changing the currency
            .SetShippingCountryRegion(null)
            .SetCurrency(currency) // Set the currency
            .SetPaymentCountryRegion(country) // Now update both the payment and shipping countries
            .SetShippingCountryRegion(country);

        _commerceApi.SaveOrder(writableOrder);

        uow.Complete();
    });
}
```

Other possibilities here are

1) After setting the shipping country to null, you could just not bother setting the shipping country to the selected country as the default tax source factory will fallback to the payment country if a shipping country isn't set.

2) If you only want to calculate taxes based on the origin location and not the destination you can change the tax source factory implementation. You'd need to do this in a composer / `IUmbracoBuilder` extension

```
builder.Services.AddUnique<ITaxSourceFactory, OriginTaxSourceFactory>();
```

**Comment by craigs100** [comment]
Interesting, this is occurring when you add a product to the cart.  At that point, there's been no other interaction with the user, so they won't have set a destination as that's set in the Checkout process.  In fact, when is an order instantiated? Is it when things are added to the cart or once the checkout process is entered?

**Comment by mattbrailsford** [comment]
The create order process will set the shipping country to be whatever the session default shipping country / stores default country is so that's likely why it'll be set even if you haven't hit the checkout process yet.

**Comment by craigs100** [comment]
Ok, I'll give your code a go and see what happens. And report back of course :)

**Comment by craigs100** [comment]
The code fixed the problem (many thanks) but appears to create another in the checkout process. When getting to the review-order stage it errors with : Cannot generate a payment form for order 0430ef65-08bf-4e3d-b8f0-018bb9428acc as it has no associated payment method. 

VendrCheckoutReviewPage.cshtml line 12 - @using (Html.BeginPaymentForm(currentOrder))

This was going through fine before the code update.  Stripe is set as the default payment method for both countries and is set as available in all countries

**Comment by mattbrailsford** [comment]
This should be raised as a separate issue, but sounds like you don't have a payment method assigned to it. Make sure your payment method is allowed in the selected country and that one is being assigned. 

Closing this issue as the reported issue is resolved by the code fix.

**Comment by craigs100** [comment]
I'm afraid not. If I remove the code you gave me, the checkout works fine. As I indicated, all payment methods are assigned and otherwise working as they have been for weeks before the client decided to switch currencies which brought up the tax issue.  Fixing the tax issue should not inject new issues, therefore the fix isn't a fix. Should that code update the payment method as well then, somehow?

**Comment by mattbrailsford** [comment]
Try this

```
var country = _commerceApi.GetCountry(store.Id, countryCode);
var currency = _commerceApi.GetCurrency(country.DefaultCurrencyId.Value);
var paymentMethod = _commerceApi.GetPaymentMethod(country.DefaultPaymentMethodId.Value);
var shippingMethod = _commerceApi.GetShippingMethod(country.DefaultShippingMethodId.Value);

_commerceApi.SetDefaultPaymentCountry(store.Id, country);
_commerceApi.SetDefaultCurrency(store.Id, currency);
_commerceApi.SetDefaultPaymentMethod(store.Id, paymentMethod);
_commerceApi.SetDefaultShippingMethod(store.Id, shippingMethod);

var order = _commerceApi.GetCurrentOrder(store.Id);
if (order != null)
{
    _commerceApi.Uow.Execute(uow =>
    {
        var writableOrder = order.AsWritable(uow)
            .SetPaymentCountryRegion(null)
            .SetShippingCountryRegion(null)
            .SetCurrency(currency)
            .SetPaymentCountryRegion(country)
            .SetShippingCountryRegion(country)
            .SetPaymentMethod(paymentMethod)
            .SetShippingMethod(shippingMethod);

        _commerceApi.SaveOrder(writableOrder);

        uow.Complete();
    });
}
```

**Comment by craigs100** [comment]
Didn't work I'm afraid. Exactly the same error.  For clarity, here's the code used....

```
    public class CurrencyChangeNotificationHandler : INotificationHandler<RoutingRequestNotification>
    {
        private readonly IVendrApi _vendrApi;
        private readonly ICurrencyService _currencyService;
        private readonly ICountryService _countryService;
        private readonly SessionManagerAccessor _sessionManagerAccessor;

        public CurrencyChangeNotificationHandler(IVendrApi vendrApi, ICurrencyService currencyService, ICountryService countryService, SessionManagerAccessor sessionManagerAccessor) {
            _vendrApi = vendrApi;
            _currencyService = currencyService;
            _countryService = countryService;
            _sessionManagerAccessor = sessionManagerAccessor;
        }

        public void Handle(RoutingRequestNotification notification)
        {
            // Change currency
            var requestBuilder = notification.RequestBuilder;
            var content = requestBuilder.PublishedContent;
            
            Guid storeId = content.AncestorOrSelf<Home>().Store.Id;
            
            var countryCode = requestBuilder.Culture.ToString().Split("-")[1];
        
            var sessionManager = _sessionManagerAccessor.Instance;
            
            /* Code from Matt to update order related data */
            var country = _vendrApi.GetCountry(storeId, countryCode);
            var currency = _vendrApi.GetCurrency(country.DefaultCurrencyId.Value);
            var paymentMethod = _vendrApi.GetPaymentMethod(country.DefaultPaymentMethodId.Value);
            var shippingMethod = _vendrApi.GetShippingMethod(country.DefaultShippingMethodId.Value);

            _vendrApi.SetDefaultPaymentCountry(storeId, country);
            _vendrApi.SetDefaultCurrency(storeId, currency);
            _vendrApi.SetDefaultPaymentMethod(storeId, paymentMethod);
            _vendrApi.SetDefaultShippingMethod(storeId, shippingMethod);

            var order = _vendrApi.GetCurrentOrder(storeId);
            if (order != null)
            {
                _vendrApi.Uow.Execute(uow =>
                {
                    var writableOrder = order.AsWritable(uow)
                        .SetPaymentCountryRegion(null)
                        .SetShippingCountryRegion(null)
                        .SetCurrency(currency)
                        .SetPaymentCountryRegion(country)
                        .SetShippingCountryRegion(country)
                        .SetPaymentMethod(paymentMethod)
                        .SetShippingMethod(shippingMethod);

                    _vendrApi.SaveOrder(writableOrder);

                    uow.Complete();
                });
            } 
            
            sessionManager.SetDefaultPaymentCountry(storeId, country);
            sessionManager.SetDefaultCurrency(storeId, currency, true);
        }
    }
```

**Comment by mattbrailsford** [comment]
Hmm, it's probably the event handlers in Vendr Checkout https://github.com/vendrhub/vendr-checkout/blob/v2/dev/src/Vendr.Checkout/Events/ResetPaymentAndShippingMethods.cs#L53-L74 these reset the payment / shipping methods whenever the countries change so you might just need to do the order updates in 2 parts

```
var order = _vendrApi.GetCurrentOrder(storeId);
if (order != null)
{
    _vendrApi.Uow.Execute(uow =>
    {
        var writableOrder = order.AsWritable(uow)
            .SetPaymentCountryRegion(null)
            .SetShippingCountryRegion(null)
            .SetCurrency(currency)
            .SetPaymentCountryRegion(country)
            .SetShippingCountryRegion(country);

        _vendrApi.SaveOrder(writableOrder);

        uow.Complete();
    });
} 

order = _vendrApi.GetCurrentOrder(storeId);
if (order != null)
{
    _vendrApi.Uow.Execute(uow =>
    {
        var writableOrder = order.AsWritable(uow)
            .SetPaymentMethod(paymentMethod)
            .SetShippingMethod(shippingMethod);

        _vendrApi.SaveOrder(writableOrder);

        uow.Complete();
    });
} 
```

**Comment by craigs100** [comment]
Brilliant! That was it. All seems to work now. Not very intuitive, I think you'd agree, but working never the less. I'm happy to put this live now and happy for the ticket to be closed.

Now I have to grovel to a rather livid client :(
