### ISSUE TITLE
Adding multiple products with equal productReference and bundleId throws an exception

### ISSUE THREAD

**Issue by rpteasolutions** [vendrhub/vendr#3]
**Describe the bug**
When trying to add multiple products with the same productReference and bundleId, .AddProduct throws an exception on the second product. 
If you do it without the bundleId is works fine. That's why I expected to be able to do it with the bundleId.

You can do this and get the expected quantity, but missing the bundleId:
**order.AddProduct( productReference, quantity );**

This will throw an exception:
**order.AddProduct( productReference, quantity, bundleId );**

I have made a workaround to check if order contains an orderline with matching productReference and bundleId, and then do: **order.AddProduct( productReference, quantity );** to get the expected result.

**Steps To Reproduce**
1. Add multiple products to order with productReference "123" and bundleId "456". Quantity can be 1 on both.
2. First product gets added to an orderline
3. Second product results in the exception

**Expected behavior**
Expected to have an orderline with a bundleId and quantity of product1's quantity + product2's quantity.

**Screenshots**
![image](https://github.com/vendrhub/vendr/assets/72739421/c5c18eb8-a12f-4b68-b18e-67f5ef8b8128)

Maybe I'm misunderstanding the use of bundleId? 🤔

**Vendr version:**
Vendr v3.0.11
Vendr Core v3.0.11

**Comment by mattbrailsford** [comment]
Bundle ID's are meant to be unique per order, hence the SQL exception. You'll need to give each bundle it's own unique ID

**Comment by mattbrailsford** [comment]
If you are trying to add the same product to an existing bundle, you'd need to use one of the `AddProductToBundle` methods. The `AddProduct` assumes you want to create a new bundle.

**Comment by rpteasolutions** [comment]
Hi Matt! Thanks for quick reply. That makes sense, I have refactored the code to use the methods as it was attended 😊
